version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'node-tropa-users-database'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
    - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
